version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

# Anchors to prevent forgetting to update a version
os_version: &os_version ubuntu20
baselibs_version: &baselibs_version v7.17.0
bcs_version: &bcs_version v11.3.0
tag_build_arg_name: &tag_build_arg_name fv3version

orbs:
  ci: geos-esm/circleci-tools@2

workflows:
  build-test:
    jobs:

      # Build fv3-container-test
      - ci/build:
          name: build-fv3-container-test-as-<< matrix.fv_precision >>-on-<< matrix.compiler >>
          context:
            - docker-hub-creds
          matrix:
            parameters:
              compiler: [ifort, gfortran]
              fv_precision: ["R4", "R8"]
          baselibs_version: *baselibs_version
          repo: fv3-container-test
          mepodevelop: false
          persist_workspace: true # Needs to be true to run fv3/gcm experiment, costs extra

      # Run FV3 standalone
      - ci/run_fv3:
          name: run-FV3-as-<< matrix.fv_precision >>-on-<< matrix.compiler >>-with-fv3-container-test
          context:
            - docker-hub-creds
          matrix:
            parameters:
              compiler: [gfortran, ifort]
              fv_precision: ["R4", "R8"]
          baselibs_version: *baselibs_version
          requires:
            - build-fv3-container-test-as-<< matrix.fv_precision >>-on-<< matrix.compiler >>
          repo: fv3-container-test

  # Build and publish docker images
  build-and-publish-docker:
    when:
      equal: [ "release", << pipeline.parameters.GHA_Event >> ]
    jobs:
      - ci/publish_docker:
          filters:
            tags:
              only: /^v.*$/
          name: publish-intel-docker-image
          context:
            - docker-hub-creds
            - ghcr-creds
          os_version: *os_version
          baselibs_version: *baselibs_version
          container_name: fv3-container-test
          mpi_name: intelmpi
          mpi_version: 2021.6.0
          compiler_name: intel
          compiler_version: 2022.1.0
          image_name: geos-env
          tag_build_arg_name: *tag_build_arg_name
          resource_class: xlarge
      - ci/publish_docker:
          filters:
            tags:
              only: /^v.*$/
          name: publish-gcc-docker-image
          context:
            - docker-hub-creds
            - ghcr-creds
          os_version: *os_version
          baselibs_version: *baselibs_version
          container_name: fv3-container-test
          mpi_name: openmpi
          mpi_version: 5.0.0
          compiler_name: gcc
          compiler_version: 12.1.0
          image_name: geos-env-mkl
          tag_build_arg_name: *tag_build_arg_name
          resource_class: xlarge
